// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using base_dao_api.Data;

#nullable disable

namespace base_dao_api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220805050719_v0.047")]
    partial class v0047
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("base_dao_api.Models.CodeDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CodeHeaderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateDttm")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("DetailCd")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdateDttm")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.HasIndex("CodeHeaderId");

                    b.HasIndex("DetailCd")
                        .IsUnique();

                    b.ToTable("CodeDetails");

                    b.HasData(
                        new
                        {
                            Id = new Guid("473c5d7c-2e4b-41a0-92ef-26d390a95ade"),
                            CodeHeaderId = new Guid("2a587862-18dd-4e07-9c5b-a62ecca1b28e"),
                            CreateDttm = new DateTime(2022, 8, 5, 5, 7, 18, 715, DateTimeKind.Utc).AddTicks(2574),
                            CreatedBy = "SYSTEM",
                            Description = "System User",
                            DetailCd = "ROLE-SYSTEM",
                            IsDeleted = false,
                            UpdateDttm = new DateTime(2022, 8, 5, 5, 7, 18, 715, DateTimeKind.Utc).AddTicks(2576),
                            UpdatedBy = "SYSTEM"
                        },
                        new
                        {
                            Id = new Guid("52c2e33d-0538-4a8a-af2c-fe48fa18a7c7"),
                            CodeHeaderId = new Guid("2a587862-18dd-4e07-9c5b-a62ecca1b28e"),
                            CreateDttm = new DateTime(2022, 8, 5, 5, 7, 18, 715, DateTimeKind.Utc).AddTicks(2580),
                            CreatedBy = "SYSTEM",
                            Description = "Admin User",
                            DetailCd = "ROLE-ADMIN",
                            IsDeleted = false,
                            UpdateDttm = new DateTime(2022, 8, 5, 5, 7, 18, 715, DateTimeKind.Utc).AddTicks(2580),
                            UpdatedBy = "SYSTEM"
                        },
                        new
                        {
                            Id = new Guid("cb6ac79c-bf90-4557-934f-6c251d1069d3"),
                            CodeHeaderId = new Guid("2a587862-18dd-4e07-9c5b-a62ecca1b28e"),
                            CreateDttm = new DateTime(2022, 8, 5, 5, 7, 18, 715, DateTimeKind.Utc).AddTicks(2583),
                            CreatedBy = "SYSTEM",
                            Description = "Normal User",
                            DetailCd = "ROLE-NORMAL",
                            IsDeleted = false,
                            UpdateDttm = new DateTime(2022, 8, 5, 5, 7, 18, 715, DateTimeKind.Utc).AddTicks(2584),
                            UpdatedBy = "SYSTEM"
                        },
                        new
                        {
                            Id = new Guid("0c855d44-a09c-46d2-9b88-56af37ff0131"),
                            CodeHeaderId = new Guid("03cf8d52-3fd5-42e8-be92-c4f65209ec52"),
                            CreateDttm = new DateTime(2022, 8, 5, 5, 7, 18, 715, DateTimeKind.Utc).AddTicks(2589),
                            CreatedBy = "SYSTEM",
                            Description = "Pool OPEN",
                            DetailCd = "PSTATUS-OPEN",
                            IsDeleted = false,
                            UpdateDttm = new DateTime(2022, 8, 5, 5, 7, 18, 715, DateTimeKind.Utc).AddTicks(2590),
                            UpdatedBy = "SYSTEM"
                        },
                        new
                        {
                            Id = new Guid("a6799ec0-0948-4c2e-bd5b-a568d611a111"),
                            CodeHeaderId = new Guid("03cf8d52-3fd5-42e8-be92-c4f65209ec52"),
                            CreateDttm = new DateTime(2022, 8, 5, 5, 7, 18, 715, DateTimeKind.Utc).AddTicks(2598),
                            CreatedBy = "SYSTEM",
                            Description = "Pool ONGOING",
                            DetailCd = "PSTATUS-ONGOING",
                            IsDeleted = false,
                            UpdateDttm = new DateTime(2022, 8, 5, 5, 7, 18, 715, DateTimeKind.Utc).AddTicks(2599),
                            UpdatedBy = "SYSTEM"
                        },
                        new
                        {
                            Id = new Guid("32e33f0a-77bf-450e-9606-da3a1e234a36"),
                            CodeHeaderId = new Guid("03cf8d52-3fd5-42e8-be92-c4f65209ec52"),
                            CreateDttm = new DateTime(2022, 8, 5, 5, 7, 18, 715, DateTimeKind.Utc).AddTicks(2601),
                            CreatedBy = "SYSTEM",
                            Description = "Pool CLOSED",
                            DetailCd = "PSTATUS-CLOSED",
                            IsDeleted = false,
                            UpdateDttm = new DateTime(2022, 8, 5, 5, 7, 18, 715, DateTimeKind.Utc).AddTicks(2601),
                            UpdatedBy = "SYSTEM"
                        });
                });

            modelBuilder.Entity("base_dao_api.Models.CodeHeader", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateDttm")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("HeaderCd")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdateDttm")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.HasIndex("HeaderCd")
                        .IsUnique();

                    b.ToTable("CodeHeaders");

                    b.HasData(
                        new
                        {
                            Id = new Guid("2a587862-18dd-4e07-9c5b-a62ecca1b28e"),
                            CreateDttm = new DateTime(2022, 8, 5, 5, 7, 18, 715, DateTimeKind.Utc).AddTicks(1836),
                            CreatedBy = "SYSTEM",
                            Description = "CodeHeader for User Roles",
                            HeaderCd = "ROLE",
                            IsDeleted = false,
                            UpdateDttm = new DateTime(2022, 8, 5, 5, 7, 18, 715, DateTimeKind.Utc).AddTicks(1840),
                            UpdatedBy = "SYSTEM"
                        },
                        new
                        {
                            Id = new Guid("03cf8d52-3fd5-42e8-be92-c4f65209ec52"),
                            CreateDttm = new DateTime(2022, 8, 5, 5, 7, 18, 715, DateTimeKind.Utc).AddTicks(1845),
                            CreatedBy = "SYSTEM",
                            Description = "CodeHeader for Pool Statuses",
                            HeaderCd = "PSTATUS",
                            IsDeleted = false,
                            UpdateDttm = new DateTime(2022, 8, 5, 5, 7, 18, 715, DateTimeKind.Utc).AddTicks(1845),
                            UpdatedBy = "SYSTEM"
                        });
                });

            modelBuilder.Entity("base_dao_api.Models.Faq", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime>("CreateDttm")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime?>("UpdateDttm")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.HasIndex("Order")
                        .IsUnique();

                    b.ToTable("Faqs");

                    b.HasData(
                        new
                        {
                            Id = new Guid("7af6632b-ee43-4891-81af-d1a8ce94a2e7"),
                            Answer = "At vero eos et accusamus et iusto",
                            CreateDttm = new DateTime(2022, 8, 5, 5, 7, 18, 715, DateTimeKind.Utc).AddTicks(3132),
                            CreatedBy = "SYSTEM",
                            IsDeleted = false,
                            Order = 1,
                            Question = "What is Wick's Crew?",
                            UpdateDttm = new DateTime(2022, 8, 5, 5, 7, 18, 715, DateTimeKind.Utc).AddTicks(3133),
                            UpdatedBy = "SYSTEM"
                        },
                        new
                        {
                            Id = new Guid("f28a411e-0423-4d32-adac-7435a9390311"),
                            Answer = "At vero eos et accusamus et iusto",
                            CreateDttm = new DateTime(2022, 8, 5, 5, 7, 18, 715, DateTimeKind.Utc).AddTicks(3136),
                            CreatedBy = "SYSTEM",
                            IsDeleted = false,
                            Order = 2,
                            Question = "What are Pooling Considerations?",
                            UpdateDttm = new DateTime(2022, 8, 5, 5, 7, 18, 715, DateTimeKind.Utc).AddTicks(3136),
                            UpdatedBy = "SYSTEM"
                        },
                        new
                        {
                            Id = new Guid("f7cedf80-f83d-40ee-8232-9a229c7e04ec"),
                            Answer = "At vero eos et accusamus et iusto",
                            CreateDttm = new DateTime(2022, 8, 5, 5, 7, 18, 715, DateTimeKind.Utc).AddTicks(3138),
                            CreatedBy = "SYSTEM",
                            IsDeleted = false,
                            Order = 3,
                            Question = "What are the Pooling Rules?",
                            UpdateDttm = new DateTime(2022, 8, 5, 5, 7, 18, 715, DateTimeKind.Utc).AddTicks(3138),
                            UpdatedBy = "SYSTEM"
                        },
                        new
                        {
                            Id = new Guid("a9b1d99d-8f57-46d6-a28a-d0c73b3faf60"),
                            Answer = "At vero eos et accusamus et iusto",
                            CreateDttm = new DateTime(2022, 8, 5, 5, 7, 18, 715, DateTimeKind.Utc).AddTicks(3140),
                            CreatedBy = "SYSTEM",
                            IsDeleted = false,
                            Order = 4,
                            Question = "What are the Available Pools?",
                            UpdateDttm = new DateTime(2022, 8, 5, 5, 7, 18, 715, DateTimeKind.Utc).AddTicks(3140),
                            UpdatedBy = "SYSTEM"
                        },
                        new
                        {
                            Id = new Guid("253c90bc-2b09-4cf4-8860-173f00692b80"),
                            Answer = "At vero eos et accusamus et iusto",
                            CreateDttm = new DateTime(2022, 8, 5, 5, 7, 18, 715, DateTimeKind.Utc).AddTicks(3141),
                            CreatedBy = "SYSTEM",
                            IsDeleted = false,
                            Order = 5,
                            Question = "How are the Funds Distributed?",
                            UpdateDttm = new DateTime(2022, 8, 5, 5, 7, 18, 715, DateTimeKind.Utc).AddTicks(3142),
                            UpdatedBy = "SYSTEM"
                        });
                });

            modelBuilder.Entity("base_dao_api.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateDttm")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime?>("UpdateDttm")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("WalletAddress")
                        .IsRequired()
                        .HasMaxLength(42)
                        .HasColumnType("nvarchar(42)");

                    b.HasKey("Id");

                    b.HasIndex("WalletAddress")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4b9f2343-55a1-4673-9344-cbfaab734761"),
                            CreateDttm = new DateTime(2022, 8, 5, 5, 7, 18, 715, DateTimeKind.Utc).AddTicks(3555),
                            CreatedBy = "SYSTEM",
                            IsDeleted = false,
                            Name = "SYSTEM",
                            UpdateDttm = new DateTime(2022, 8, 5, 5, 7, 18, 715, DateTimeKind.Utc).AddTicks(3556),
                            UpdatedBy = "SYSTEM",
                            WalletAddress = "0x8c268f32D7F129ac0D9FB1E5B490d90810dFa446"
                        },
                        new
                        {
                            Id = new Guid("7659b3b7-bd60-4082-9d9d-226637e997d2"),
                            CreateDttm = new DateTime(2022, 8, 5, 5, 7, 18, 715, DateTimeKind.Utc).AddTicks(3564),
                            CreatedBy = "SYSTEM",
                            IsDeleted = false,
                            Name = "ADMIN-1",
                            UpdateDttm = new DateTime(2022, 8, 5, 5, 7, 18, 715, DateTimeKind.Utc).AddTicks(3564),
                            UpdatedBy = "SYSTEM",
                            WalletAddress = "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266"
                        });
                });

            modelBuilder.Entity("base_dao_api.Models.UserRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateDttm")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdateDttm")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("UserRoles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("cca114f4-fd13-415b-ab9f-c7b38826047c"),
                            CreateDttm = new DateTime(2022, 8, 5, 5, 7, 18, 715, DateTimeKind.Utc).AddTicks(4746),
                            CreatedBy = "SYSTEM",
                            IsDeleted = false,
                            RoleId = new Guid("473c5d7c-2e4b-41a0-92ef-26d390a95ade"),
                            UpdateDttm = new DateTime(2022, 8, 5, 5, 7, 18, 715, DateTimeKind.Utc).AddTicks(4747),
                            UpdatedBy = "SYSTEM",
                            UserId = new Guid("4b9f2343-55a1-4673-9344-cbfaab734761")
                        },
                        new
                        {
                            Id = new Guid("1bb78a7f-8cb0-4c97-ab33-08defd957c62"),
                            CreateDttm = new DateTime(2022, 8, 5, 5, 7, 18, 715, DateTimeKind.Utc).AddTicks(4750),
                            CreatedBy = "SYSTEM",
                            IsDeleted = false,
                            RoleId = new Guid("52c2e33d-0538-4a8a-af2c-fe48fa18a7c7"),
                            UpdateDttm = new DateTime(2022, 8, 5, 5, 7, 18, 715, DateTimeKind.Utc).AddTicks(4750),
                            UpdatedBy = "SYSTEM",
                            UserId = new Guid("7659b3b7-bd60-4082-9d9d-226637e997d2")
                        });
                });

            modelBuilder.Entity("base_dao_api.Models.CodeDetail", b =>
                {
                    b.HasOne("base_dao_api.Models.CodeHeader", "CodeHeader")
                        .WithMany("CodeDetails")
                        .HasForeignKey("CodeHeaderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CodeHeader");
                });

            modelBuilder.Entity("base_dao_api.Models.UserRole", b =>
                {
                    b.HasOne("base_dao_api.Models.CodeDetail", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("base_dao_api.Models.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("base_dao_api.Models.CodeHeader", b =>
                {
                    b.Navigation("CodeDetails");
                });

            modelBuilder.Entity("base_dao_api.Models.User", b =>
                {
                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
