// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using base_dao_api.Data;

#nullable disable

namespace base_dao_api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220803153653_v0.034")]
    partial class v0034
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("base_dao_api.Models.CodeDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CodeHeaderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateDttm")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreateUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("DetailCd")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UpdateDttm")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UpdateUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CodeHeaderId");

                    b.ToTable("CodeDetails");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8b820d54-bed7-4b81-a27d-e4b336cf76a9"),
                            CodeHeaderId = new Guid("3d9c3987-7738-4606-a3f2-6c8014a99cf7"),
                            CreateDttm = new DateTime(2022, 8, 3, 23, 36, 52, 869, DateTimeKind.Local).AddTicks(5278),
                            CreateUserId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Description = "Admin User",
                            DetailCd = "ROLE-ADMIN",
                            IsActive = true,
                            UpdateDttm = new DateTime(2022, 8, 3, 23, 36, 52, 869, DateTimeKind.Local).AddTicks(5278),
                            UpdateUserId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("249672e7-e39b-4cb6-84c6-5c99e4e5d939"),
                            CodeHeaderId = new Guid("3d9c3987-7738-4606-a3f2-6c8014a99cf7"),
                            CreateDttm = new DateTime(2022, 8, 3, 23, 36, 52, 869, DateTimeKind.Local).AddTicks(5282),
                            CreateUserId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Description = "Normal User",
                            DetailCd = "ROLE-NORMAL",
                            IsActive = true,
                            UpdateDttm = new DateTime(2022, 8, 3, 23, 36, 52, 869, DateTimeKind.Local).AddTicks(5283),
                            UpdateUserId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("00226a3e-9cd9-4de7-a6e6-15b7585094e3"),
                            CodeHeaderId = new Guid("827126e4-cc9d-4c09-a0bc-ffd45246ed5f"),
                            CreateDttm = new DateTime(2022, 8, 3, 23, 36, 52, 869, DateTimeKind.Local).AddTicks(5284),
                            CreateUserId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Description = "Pool OPEN",
                            DetailCd = "PSTATUS-OPEN",
                            IsActive = true,
                            UpdateDttm = new DateTime(2022, 8, 3, 23, 36, 52, 869, DateTimeKind.Local).AddTicks(5285),
                            UpdateUserId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("e9e164ad-eb5f-4da6-b6d9-fde9c46ea15b"),
                            CodeHeaderId = new Guid("827126e4-cc9d-4c09-a0bc-ffd45246ed5f"),
                            CreateDttm = new DateTime(2022, 8, 3, 23, 36, 52, 869, DateTimeKind.Local).AddTicks(5287),
                            CreateUserId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Description = "Pool ONGOING",
                            DetailCd = "PSTATUS-ONGOING",
                            IsActive = true,
                            UpdateDttm = new DateTime(2022, 8, 3, 23, 36, 52, 869, DateTimeKind.Local).AddTicks(5287),
                            UpdateUserId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("5fe8c5c0-678d-48fb-8460-3cb305a22bc7"),
                            CodeHeaderId = new Guid("827126e4-cc9d-4c09-a0bc-ffd45246ed5f"),
                            CreateDttm = new DateTime(2022, 8, 3, 23, 36, 52, 869, DateTimeKind.Local).AddTicks(5289),
                            CreateUserId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Description = "Pool CLOSED",
                            DetailCd = "PSTATUS-CLOSED",
                            IsActive = true,
                            UpdateDttm = new DateTime(2022, 8, 3, 23, 36, 52, 869, DateTimeKind.Local).AddTicks(5289),
                            UpdateUserId = new Guid("00000000-0000-0000-0000-000000000000")
                        });
                });

            modelBuilder.Entity("base_dao_api.Models.CodeHeader", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateDttm")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreateUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("HeaderCd")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UpdateDttm")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UpdateUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("CodeHeaders");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3d9c3987-7738-4606-a3f2-6c8014a99cf7"),
                            CreateDttm = new DateTime(2022, 8, 3, 23, 36, 52, 869, DateTimeKind.Local).AddTicks(5206),
                            CreateUserId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Description = "CodeHeader for User Roles",
                            HeaderCd = "ROLE",
                            IsActive = true,
                            UpdateDttm = new DateTime(2022, 8, 3, 23, 36, 52, 869, DateTimeKind.Local).AddTicks(5216),
                            UpdateUserId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("827126e4-cc9d-4c09-a0bc-ffd45246ed5f"),
                            CreateDttm = new DateTime(2022, 8, 3, 23, 36, 52, 869, DateTimeKind.Local).AddTicks(5225),
                            CreateUserId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Description = "CodeHeader for Pool Statuses",
                            HeaderCd = "PSTATUS",
                            IsActive = true,
                            UpdateDttm = new DateTime(2022, 8, 3, 23, 36, 52, 869, DateTimeKind.Local).AddTicks(5226),
                            UpdateUserId = new Guid("00000000-0000-0000-0000-000000000000")
                        });
                });

            modelBuilder.Entity("base_dao_api.Models.Faq", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime>("CreateDttm")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreateUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime>("UpdateDttm")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UpdateUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Faqs");

                    b.HasData(
                        new
                        {
                            Id = new Guid("21416605-9092-426f-a607-369e5ba1a80f"),
                            Answer = "At vero eos et accusamus et iusto",
                            CreateDttm = new DateTime(2022, 8, 3, 23, 36, 52, 869, DateTimeKind.Local).AddTicks(5349),
                            CreateUserId = new Guid("00000000-0000-0000-0000-000000000000"),
                            IsActive = true,
                            Question = "What is Wick's Crew?",
                            UpdateDttm = new DateTime(2022, 8, 3, 23, 36, 52, 869, DateTimeKind.Local).AddTicks(5349),
                            UpdateUserId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("5c84eab0-5532-4a21-afa6-088c6f150569"),
                            Answer = "At vero eos et accusamus et iusto",
                            CreateDttm = new DateTime(2022, 8, 3, 23, 36, 52, 869, DateTimeKind.Local).AddTicks(5352),
                            CreateUserId = new Guid("00000000-0000-0000-0000-000000000000"),
                            IsActive = true,
                            Question = "What are Pooling Considerations?",
                            UpdateDttm = new DateTime(2022, 8, 3, 23, 36, 52, 869, DateTimeKind.Local).AddTicks(5353),
                            UpdateUserId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("34d21343-3ee0-4862-b3cb-bd7efaee1a2c"),
                            Answer = "At vero eos et accusamus et iusto",
                            CreateDttm = new DateTime(2022, 8, 3, 23, 36, 52, 869, DateTimeKind.Local).AddTicks(5354),
                            CreateUserId = new Guid("00000000-0000-0000-0000-000000000000"),
                            IsActive = true,
                            Question = "What are the Pooling Rules?",
                            UpdateDttm = new DateTime(2022, 8, 3, 23, 36, 52, 869, DateTimeKind.Local).AddTicks(5354),
                            UpdateUserId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("028af00a-ae31-4ca0-8cc5-1e8147151404"),
                            Answer = "At vero eos et accusamus et iusto",
                            CreateDttm = new DateTime(2022, 8, 3, 23, 36, 52, 869, DateTimeKind.Local).AddTicks(5356),
                            CreateUserId = new Guid("00000000-0000-0000-0000-000000000000"),
                            IsActive = true,
                            Question = "What are the Available Pools?",
                            UpdateDttm = new DateTime(2022, 8, 3, 23, 36, 52, 869, DateTimeKind.Local).AddTicks(5356),
                            UpdateUserId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("253abe0a-2fa5-4601-946c-6742de41285a"),
                            Answer = "At vero eos et accusamus et iusto",
                            CreateDttm = new DateTime(2022, 8, 3, 23, 36, 52, 869, DateTimeKind.Local).AddTicks(5358),
                            CreateUserId = new Guid("00000000-0000-0000-0000-000000000000"),
                            IsActive = true,
                            Question = "How are the Funds Distributed?",
                            UpdateDttm = new DateTime(2022, 8, 3, 23, 36, 52, 869, DateTimeKind.Local).AddTicks(5358),
                            UpdateUserId = new Guid("00000000-0000-0000-0000-000000000000")
                        });
                });

            modelBuilder.Entity("base_dao_api.Models.Movie", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Instructor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("SuperheroId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SuperheroId");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = new Guid("12d36223-9141-4887-8b3a-7d9e2b8ca453"),
                            Description = "Batman Begins is a 2005 superhero film directed by Christopher Nolan and written by Nolan and David S. Goyer. Based on the DC Comics character Batman, it stars Christian Bale as Bruce Wayne / Batman, with Michael Caine, Liam Neeson, Katie Holmes, Gary Oldman,",
                            Instructor = "Christopher Nolan",
                            ReleaseDate = new DateTime(2005, 6, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SuperheroId = new Guid("70dca383-9dd8-47d9-bce8-580dcc2c709b"),
                            Title = "Batman Begins"
                        },
                        new
                        {
                            Id = new Guid("e564c490-d44c-4181-8df0-5a6ea74dafc1"),
                            Description = "The Dark Knight is a 2008 superhero film directed, produced, and co-written by Christopher Nolan. Based on the DC Comics character Batman, the film is the second installment of Nolan's The Dark Knight Trilogy and a sequel to 2005's Batman Begins, starring Christian Bale and supported by Michael Caine, Heath Ledger, Gary Oldman, Aaron Eckhart, Maggie Gyllenhaal, and Morgan Freeman.",
                            Instructor = "Christopher Nolan",
                            ReleaseDate = new DateTime(2008, 7, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SuperheroId = new Guid("70dca383-9dd8-47d9-bce8-580dcc2c709b"),
                            Title = "The Dark Knight"
                        },
                        new
                        {
                            Id = new Guid("03c9dc0a-0745-43a9-ac4e-c6545974697b"),
                            Description = "The Dark Knight Rises is a 2012 superhero film directed by Christopher Nolan, who co-wrote the screenplay with his brother Jonathan Nolan, and the story with David S. Goyer.",
                            Instructor = "Christopher Nolan",
                            ReleaseDate = new DateTime(2012, 7, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SuperheroId = new Guid("70dca383-9dd8-47d9-bce8-580dcc2c709b"),
                            Title = "The Dark Knight Rises"
                        },
                        new
                        {
                            Id = new Guid("2a4c60a7-0ff9-412b-a8ff-03c946ee2c57"),
                            Description = "Star Wars (retroactively titled Star Wars: Episode IV – A New Hope) is a 1977 American epic space opera film written and directed by George Lucas, produced by Lucasfilm and distributed by 20th Century Fox.",
                            Instructor = "George Lucas",
                            ReleaseDate = new DateTime(1977, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SuperheroId = new Guid("04a8eab7-41af-4fa3-85d5-8e5c9d1fca4b"),
                            Title = "Star Wars: Episode IV – A New Hope"
                        },
                        new
                        {
                            Id = new Guid("bf251862-32d2-49a2-84eb-fc5c7d3ad7a2"),
                            Description = "The Empire Strikes Back (also known as Star Wars: Episode V – The Empire Strikes Back) is a 1980 American epic space opera film directed by Irvin Kershner and written by Leigh Brackett and Lawrence Kasdan, based on a story by George Lucas.",
                            Instructor = "Irvin Kershner",
                            ReleaseDate = new DateTime(1980, 5, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SuperheroId = new Guid("04a8eab7-41af-4fa3-85d5-8e5c9d1fca4b"),
                            Title = "Star Wars: Episode V – The Empire Strikes Back"
                        },
                        new
                        {
                            Id = new Guid("718980d0-08e1-466e-aba3-c421a7bef58e"),
                            Description = "Return of the Jedi (also known as Star Wars: Episode VI – Return of the Jedi) is a 1983 American epic space opera film directed by Richard Marquand. The screenplay is by Lawrence Kasdan and George Lucas from a story by Lucas, who was also the executive producer.",
                            Instructor = "Richard Marquand",
                            ReleaseDate = new DateTime(1983, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SuperheroId = new Guid("04a8eab7-41af-4fa3-85d5-8e5c9d1fca4b"),
                            Title = "Star Wars: Episode VI – Return of the Jedi"
                        },
                        new
                        {
                            Id = new Guid("26b65732-549f-44f7-87e9-f99af7b598f2"),
                            Description = "Black Widow is a 2021 American superhero film based on Marvel Comics featuring the character of the same name. Produced by Marvel Studios and distributed by Walt Disney Studios Motion Pictures, it is the 24th film in the Marvel Cinematic Universe (MCU).",
                            Instructor = "Cate Shortland",
                            ReleaseDate = new DateTime(2021, 6, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SuperheroId = new Guid("3694f37f-1b1c-4025-9b39-169e31441548"),
                            Title = "Black Widow"
                        });
                });

            modelBuilder.Entity("base_dao_api.Models.Superhero", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Height")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Superheroes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("70dca383-9dd8-47d9-bce8-580dcc2c709b"),
                            Description = "Batman was originally introduced as a ruthless vigilante who frequently killed or maimed criminals, but evolved into a character with a stringent moral code and strong sense of justice. Unlike most superheroes, Batman does not possess any superpowers, instead relying on his intellect, fighting skills, and wealth.",
                            Height = 1.9299999999999999,
                            Name = "Batman"
                        },
                        new
                        {
                            Id = new Guid("04a8eab7-41af-4fa3-85d5-8e5c9d1fca4b"),
                            Description = "Luke Skywalker was a Tatooine farmboy who rose from humble beginnings to become one of the greatest Jedi the galaxy has ever known. Along with his friends Princess Leia and Han Solo, Luke battled the evil Empire, discovered the truth of his parentage, and ended the tyranny of the Sith.",
                            Height = 1.7,
                            Name = "Luke Skywalker"
                        },
                        new
                        {
                            Id = new Guid("3694f37f-1b1c-4025-9b39-169e31441548"),
                            Description = "Black Widow, real name Natasha Romanoff, is a trained female secret agent and superhero that appears in Marvel Comics. Associated with the superhero teams S.H.I.E.L.D. and the Avengers, Black Widow makes up for her lack of superpowers with world class training as an athlete, acrobat, and expert martial artist and weapon specialist.",
                            Height = 1.7,
                            Name = "Black Widow"
                        });
                });

            modelBuilder.Entity("base_dao_api.Models.Superpower", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SuperPower")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("SuperheroId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SuperheroId");

                    b.ToTable("Superpowers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b95d6c77-43e2-4589-9804-430c264cea68"),
                            Description = "He's always a step ahead.",
                            SuperPower = "Intellect.",
                            SuperheroId = new Guid("70dca383-9dd8-47d9-bce8-580dcc2c709b")
                        },
                        new
                        {
                            Id = new Guid("f724aa8d-acc9-48b9-86cd-39617551cfdd"),
                            Description = "Sublime fighting skills.",
                            SuperPower = "Fighting",
                            SuperheroId = new Guid("70dca383-9dd8-47d9-bce8-580dcc2c709b")
                        },
                        new
                        {
                            Id = new Guid("937cfe45-d1d8-4f3d-a0c1-5a42dc05e1ef"),
                            Description = "He got a lot of money",
                            SuperPower = "Wealth.",
                            SuperheroId = new Guid("70dca383-9dd8-47d9-bce8-580dcc2c709b")
                        },
                        new
                        {
                            Id = new Guid("977ff932-6c47-4aca-a861-fdeff06a4c8c"),
                            Description = "Skywalker is able to deflect fire from a blaster back at the opponent firing. This enables Luke to turn someone else's weapon against them.",
                            SuperPower = "Deflect blaster power.",
                            SuperheroId = new Guid("04a8eab7-41af-4fa3-85d5-8e5c9d1fca4b")
                        },
                        new
                        {
                            Id = new Guid("67474698-6f26-4725-8068-9cb5f292cebf"),
                            Description = "She's good at spying at people.",
                            SuperPower = "Espionage",
                            SuperheroId = new Guid("3694f37f-1b1c-4025-9b39-169e31441548")
                        },
                        new
                        {
                            Id = new Guid("32638fac-4043-4496-a1af-eaaae23128bc"),
                            Description = "She knows how to infiltrate the enemy.",
                            SuperPower = "Infiltration",
                            SuperheroId = new Guid("3694f37f-1b1c-4025-9b39-169e31441548")
                        },
                        new
                        {
                            Id = new Guid("0712d23d-f8e6-4699-a9a1-d60bbafb3fed"),
                            Description = "The knowledge of how to undermine others.",
                            SuperPower = "Subterfuge",
                            SuperheroId = new Guid("3694f37f-1b1c-4025-9b39-169e31441548")
                        });
                });

            modelBuilder.Entity("base_dao_api.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateDttm")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreateUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UpdateDttm")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UpdateUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("WalletAddress")
                        .IsRequired()
                        .HasMaxLength(42)
                        .HasColumnType("nvarchar(42)");

                    b.HasKey("Id");

                    b.HasIndex("WalletAddress")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4d000aac-5d88-4d68-b5da-746219fb58d4"),
                            CreateDttm = new DateTime(2022, 8, 3, 23, 36, 52, 869, DateTimeKind.Local).AddTicks(6487),
                            CreateUserId = new Guid("00000000-0000-0000-0000-000000000000"),
                            IsActive = true,
                            UpdateDttm = new DateTime(2022, 8, 3, 23, 36, 52, 869, DateTimeKind.Local).AddTicks(6491),
                            UpdateUserId = new Guid("00000000-0000-0000-0000-000000000000"),
                            WalletAddress = "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266"
                        });
                });

            modelBuilder.Entity("base_dao_api.Models.UserRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CodeDetailId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateDttm")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreateUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UpdateDttm")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UpdateUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CodeDetailId");

                    b.HasIndex("UserId");

                    b.ToTable("UserRole");
                });

            modelBuilder.Entity("base_dao_api.Models.CodeDetail", b =>
                {
                    b.HasOne("base_dao_api.Models.CodeHeader", "CodeHeader")
                        .WithMany("CodeDetails")
                        .HasForeignKey("CodeHeaderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CodeHeader");
                });

            modelBuilder.Entity("base_dao_api.Models.Movie", b =>
                {
                    b.HasOne("base_dao_api.Models.Superhero", "Superhero")
                        .WithMany("Movies")
                        .HasForeignKey("SuperheroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Superhero");
                });

            modelBuilder.Entity("base_dao_api.Models.Superpower", b =>
                {
                    b.HasOne("base_dao_api.Models.Superhero", "Superhero")
                        .WithMany("Superpowers")
                        .HasForeignKey("SuperheroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Superhero");
                });

            modelBuilder.Entity("base_dao_api.Models.UserRole", b =>
                {
                    b.HasOne("base_dao_api.Models.CodeDetail", "CodeDetail")
                        .WithMany()
                        .HasForeignKey("CodeDetailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("base_dao_api.Models.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CodeDetail");

                    b.Navigation("User");
                });

            modelBuilder.Entity("base_dao_api.Models.CodeHeader", b =>
                {
                    b.Navigation("CodeDetails");
                });

            modelBuilder.Entity("base_dao_api.Models.Superhero", b =>
                {
                    b.Navigation("Movies");

                    b.Navigation("Superpowers");
                });

            modelBuilder.Entity("base_dao_api.Models.User", b =>
                {
                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
