// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using base_dao_api.Data;

#nullable disable

namespace base_dao_api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220805050116_v0.046")]
    partial class v0046
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("base_dao_api.Models.CodeDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CodeHeaderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateDttm")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("DetailCd")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdateDttm")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.HasIndex("CodeHeaderId");

                    b.HasIndex("DetailCd")
                        .IsUnique();

                    b.ToTable("CodeDetails");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b6a01cff-8b18-41a6-906b-817126763b73"),
                            CodeHeaderId = new Guid("5aeaa24b-8168-49c7-9305-a468f0c37a49"),
                            CreateDttm = new DateTime(2022, 8, 5, 5, 1, 16, 207, DateTimeKind.Utc).AddTicks(6540),
                            CreatedBy = "SYSTEM",
                            Description = "Admin User",
                            DetailCd = "ROLE-SYSTEM",
                            IsDeleted = false,
                            UpdateDttm = new DateTime(2022, 8, 5, 5, 1, 16, 207, DateTimeKind.Utc).AddTicks(6540),
                            UpdatedBy = "SYSTEM"
                        },
                        new
                        {
                            Id = new Guid("c48d573f-a79f-46a7-8ca2-06cd1db0b8ec"),
                            CodeHeaderId = new Guid("5aeaa24b-8168-49c7-9305-a468f0c37a49"),
                            CreateDttm = new DateTime(2022, 8, 5, 5, 1, 16, 207, DateTimeKind.Utc).AddTicks(6543),
                            CreatedBy = "SYSTEM",
                            Description = "Admin User",
                            DetailCd = "ROLE-ADMIN",
                            IsDeleted = false,
                            UpdateDttm = new DateTime(2022, 8, 5, 5, 1, 16, 207, DateTimeKind.Utc).AddTicks(6543),
                            UpdatedBy = "SYSTEM"
                        },
                        new
                        {
                            Id = new Guid("a52cb15a-0bf0-44b9-9750-6b90ade160d3"),
                            CodeHeaderId = new Guid("5aeaa24b-8168-49c7-9305-a468f0c37a49"),
                            CreateDttm = new DateTime(2022, 8, 5, 5, 1, 16, 207, DateTimeKind.Utc).AddTicks(6550),
                            CreatedBy = "SYSTEM",
                            Description = "Normal User",
                            DetailCd = "ROLE-NORMAL",
                            IsDeleted = false,
                            UpdateDttm = new DateTime(2022, 8, 5, 5, 1, 16, 207, DateTimeKind.Utc).AddTicks(6551),
                            UpdatedBy = "SYSTEM"
                        },
                        new
                        {
                            Id = new Guid("fcb4d963-9746-4d98-9203-e6ee6afddc72"),
                            CodeHeaderId = new Guid("bc9cc106-8cdc-45ae-af8b-9964a6a9da6e"),
                            CreateDttm = new DateTime(2022, 8, 5, 5, 1, 16, 207, DateTimeKind.Utc).AddTicks(6553),
                            CreatedBy = "SYSTEM",
                            Description = "Pool OPEN",
                            DetailCd = "PSTATUS-OPEN",
                            IsDeleted = false,
                            UpdateDttm = new DateTime(2022, 8, 5, 5, 1, 16, 207, DateTimeKind.Utc).AddTicks(6553),
                            UpdatedBy = "SYSTEM"
                        },
                        new
                        {
                            Id = new Guid("7d76fcbc-0718-4e98-b6fb-7e8623bb31c3"),
                            CodeHeaderId = new Guid("bc9cc106-8cdc-45ae-af8b-9964a6a9da6e"),
                            CreateDttm = new DateTime(2022, 8, 5, 5, 1, 16, 207, DateTimeKind.Utc).AddTicks(6555),
                            CreatedBy = "SYSTEM",
                            Description = "Pool ONGOING",
                            DetailCd = "PSTATUS-ONGOING",
                            IsDeleted = false,
                            UpdateDttm = new DateTime(2022, 8, 5, 5, 1, 16, 207, DateTimeKind.Utc).AddTicks(6555),
                            UpdatedBy = "SYSTEM"
                        },
                        new
                        {
                            Id = new Guid("8be5b810-defc-4603-80a3-18498522c2af"),
                            CodeHeaderId = new Guid("bc9cc106-8cdc-45ae-af8b-9964a6a9da6e"),
                            CreateDttm = new DateTime(2022, 8, 5, 5, 1, 16, 207, DateTimeKind.Utc).AddTicks(6557),
                            CreatedBy = "SYSTEM",
                            Description = "Pool CLOSED",
                            DetailCd = "PSTATUS-CLOSED",
                            IsDeleted = false,
                            UpdateDttm = new DateTime(2022, 8, 5, 5, 1, 16, 207, DateTimeKind.Utc).AddTicks(6557),
                            UpdatedBy = "SYSTEM"
                        });
                });

            modelBuilder.Entity("base_dao_api.Models.CodeHeader", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateDttm")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("HeaderCd")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdateDttm")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.HasIndex("HeaderCd")
                        .IsUnique();

                    b.ToTable("CodeHeaders");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5aeaa24b-8168-49c7-9305-a468f0c37a49"),
                            CreateDttm = new DateTime(2022, 8, 5, 5, 1, 16, 207, DateTimeKind.Utc).AddTicks(5917),
                            CreatedBy = "SYSTEM",
                            Description = "CodeHeader for User Roles",
                            HeaderCd = "ROLE",
                            IsDeleted = false,
                            UpdateDttm = new DateTime(2022, 8, 5, 5, 1, 16, 207, DateTimeKind.Utc).AddTicks(5918),
                            UpdatedBy = "SYSTEM"
                        },
                        new
                        {
                            Id = new Guid("bc9cc106-8cdc-45ae-af8b-9964a6a9da6e"),
                            CreateDttm = new DateTime(2022, 8, 5, 5, 1, 16, 207, DateTimeKind.Utc).AddTicks(5923),
                            CreatedBy = "SYSTEM",
                            Description = "CodeHeader for Pool Statuses",
                            HeaderCd = "PSTATUS",
                            IsDeleted = false,
                            UpdateDttm = new DateTime(2022, 8, 5, 5, 1, 16, 207, DateTimeKind.Utc).AddTicks(5923),
                            UpdatedBy = "SYSTEM"
                        });
                });

            modelBuilder.Entity("base_dao_api.Models.Faq", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime>("CreateDttm")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime?>("UpdateDttm")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.HasIndex("Order")
                        .IsUnique();

                    b.ToTable("Faqs");

                    b.HasData(
                        new
                        {
                            Id = new Guid("2b7f9a5c-a197-45ee-aca6-8aabfcea2216"),
                            Answer = "At vero eos et accusamus et iusto",
                            CreateDttm = new DateTime(2022, 8, 5, 5, 1, 16, 207, DateTimeKind.Utc).AddTicks(7060),
                            CreatedBy = "SYSTEM",
                            IsDeleted = false,
                            Order = 1,
                            Question = "What is Wick's Crew?",
                            UpdateDttm = new DateTime(2022, 8, 5, 5, 1, 16, 207, DateTimeKind.Utc).AddTicks(7061),
                            UpdatedBy = "SYSTEM"
                        },
                        new
                        {
                            Id = new Guid("1c1c215e-7df5-4eaa-bd9c-f0ccc1d5908e"),
                            Answer = "At vero eos et accusamus et iusto",
                            CreateDttm = new DateTime(2022, 8, 5, 5, 1, 16, 207, DateTimeKind.Utc).AddTicks(7064),
                            CreatedBy = "SYSTEM",
                            IsDeleted = false,
                            Order = 2,
                            Question = "What are Pooling Considerations?",
                            UpdateDttm = new DateTime(2022, 8, 5, 5, 1, 16, 207, DateTimeKind.Utc).AddTicks(7064),
                            UpdatedBy = "SYSTEM"
                        },
                        new
                        {
                            Id = new Guid("207b1456-cf51-4d45-9846-321b8179f9da"),
                            Answer = "At vero eos et accusamus et iusto",
                            CreateDttm = new DateTime(2022, 8, 5, 5, 1, 16, 207, DateTimeKind.Utc).AddTicks(7065),
                            CreatedBy = "SYSTEM",
                            IsDeleted = false,
                            Order = 3,
                            Question = "What are the Pooling Rules?",
                            UpdateDttm = new DateTime(2022, 8, 5, 5, 1, 16, 207, DateTimeKind.Utc).AddTicks(7066),
                            UpdatedBy = "SYSTEM"
                        },
                        new
                        {
                            Id = new Guid("f731c6a6-110b-4cc3-afee-43eaff457910"),
                            Answer = "At vero eos et accusamus et iusto",
                            CreateDttm = new DateTime(2022, 8, 5, 5, 1, 16, 207, DateTimeKind.Utc).AddTicks(7067),
                            CreatedBy = "SYSTEM",
                            IsDeleted = false,
                            Order = 4,
                            Question = "What are the Available Pools?",
                            UpdateDttm = new DateTime(2022, 8, 5, 5, 1, 16, 207, DateTimeKind.Utc).AddTicks(7067),
                            UpdatedBy = "SYSTEM"
                        },
                        new
                        {
                            Id = new Guid("51dbae03-805d-4242-8ef1-02efb10a5168"),
                            Answer = "At vero eos et accusamus et iusto",
                            CreateDttm = new DateTime(2022, 8, 5, 5, 1, 16, 207, DateTimeKind.Utc).AddTicks(7072),
                            CreatedBy = "SYSTEM",
                            IsDeleted = false,
                            Order = 5,
                            Question = "How are the Funds Distributed?",
                            UpdateDttm = new DateTime(2022, 8, 5, 5, 1, 16, 207, DateTimeKind.Utc).AddTicks(7073),
                            UpdatedBy = "SYSTEM"
                        });
                });

            modelBuilder.Entity("base_dao_api.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateDttm")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime?>("UpdateDttm")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("WalletAddress")
                        .IsRequired()
                        .HasMaxLength(42)
                        .HasColumnType("nvarchar(42)");

                    b.HasKey("Id");

                    b.HasIndex("WalletAddress")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("9683e940-7b90-4042-9644-12366e58f384"),
                            CreateDttm = new DateTime(2022, 8, 5, 5, 1, 16, 207, DateTimeKind.Utc).AddTicks(7470),
                            CreatedBy = "SYSTEM",
                            IsDeleted = false,
                            Name = "SYSTEM",
                            UpdateDttm = new DateTime(2022, 8, 5, 5, 1, 16, 207, DateTimeKind.Utc).AddTicks(7471),
                            UpdatedBy = "SYSTEM",
                            WalletAddress = "0x8c268f32D7F129ac0D9FB1E5B490d90810dFa446"
                        },
                        new
                        {
                            Id = new Guid("abd61b3c-8f38-4b39-bdc3-4b536fd8aab2"),
                            CreateDttm = new DateTime(2022, 8, 5, 5, 1, 16, 207, DateTimeKind.Utc).AddTicks(7475),
                            CreatedBy = "SYSTEM",
                            IsDeleted = false,
                            Name = "ADMIN-1",
                            UpdateDttm = new DateTime(2022, 8, 5, 5, 1, 16, 207, DateTimeKind.Utc).AddTicks(7475),
                            UpdatedBy = "SYSTEM",
                            WalletAddress = "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266"
                        });
                });

            modelBuilder.Entity("base_dao_api.Models.UserRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateDttm")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdateDttm")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("UserRoles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("369988ce-c583-4bc8-801f-38e60259da0e"),
                            CreateDttm = new DateTime(2022, 8, 5, 5, 1, 16, 207, DateTimeKind.Utc).AddTicks(8525),
                            CreatedBy = "SYSTEM",
                            IsDeleted = false,
                            RoleId = new Guid("b6a01cff-8b18-41a6-906b-817126763b73"),
                            UpdateDttm = new DateTime(2022, 8, 5, 5, 1, 16, 207, DateTimeKind.Utc).AddTicks(8526),
                            UpdatedBy = "SYSTEM",
                            UserId = new Guid("9683e940-7b90-4042-9644-12366e58f384")
                        },
                        new
                        {
                            Id = new Guid("6d43294f-f9d2-440d-b7bd-0957944bdefa"),
                            CreateDttm = new DateTime(2022, 8, 5, 5, 1, 16, 207, DateTimeKind.Utc).AddTicks(8528),
                            CreatedBy = "SYSTEM",
                            IsDeleted = false,
                            RoleId = new Guid("c48d573f-a79f-46a7-8ca2-06cd1db0b8ec"),
                            UpdateDttm = new DateTime(2022, 8, 5, 5, 1, 16, 207, DateTimeKind.Utc).AddTicks(8528),
                            UpdatedBy = "SYSTEM",
                            UserId = new Guid("abd61b3c-8f38-4b39-bdc3-4b536fd8aab2")
                        });
                });

            modelBuilder.Entity("base_dao_api.Models.CodeDetail", b =>
                {
                    b.HasOne("base_dao_api.Models.CodeHeader", "CodeHeader")
                        .WithMany("CodeDetails")
                        .HasForeignKey("CodeHeaderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CodeHeader");
                });

            modelBuilder.Entity("base_dao_api.Models.UserRole", b =>
                {
                    b.HasOne("base_dao_api.Models.CodeDetail", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("base_dao_api.Models.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("base_dao_api.Models.CodeHeader", b =>
                {
                    b.Navigation("CodeDetails");
                });

            modelBuilder.Entity("base_dao_api.Models.User", b =>
                {
                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
