// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using base_dao_api.Data;

#nullable disable

namespace base_dao_api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220808112054_v0.051")]
    partial class v0051
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("base_dao_api.Models.Faq", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime>("CreateDttm")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime?>("UpdateDttm")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.HasIndex("Order")
                        .IsUnique();

                    b.ToTable("Faqs");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a9c56e9a-8936-4328-9e96-3ddc2aa162f5"),
                            Answer = "At vero eos et accusamus et iusto",
                            CreateDttm = new DateTime(2022, 8, 8, 11, 20, 54, 232, DateTimeKind.Utc).AddTicks(7477),
                            CreatedBy = "SYSTEM",
                            IsDeleted = false,
                            Order = 1,
                            Question = "What is Wick's Crew?",
                            UpdateDttm = new DateTime(2022, 8, 8, 11, 20, 54, 232, DateTimeKind.Utc).AddTicks(7480),
                            UpdatedBy = "SYSTEM"
                        },
                        new
                        {
                            Id = new Guid("96976919-943b-43c7-bc73-6c5ff8f2eec3"),
                            Answer = "At vero eos et accusamus et iusto",
                            CreateDttm = new DateTime(2022, 8, 8, 11, 20, 54, 232, DateTimeKind.Utc).AddTicks(7484),
                            CreatedBy = "SYSTEM",
                            IsDeleted = false,
                            Order = 2,
                            Question = "What are Pooling Considerations?",
                            UpdateDttm = new DateTime(2022, 8, 8, 11, 20, 54, 232, DateTimeKind.Utc).AddTicks(7484),
                            UpdatedBy = "SYSTEM"
                        },
                        new
                        {
                            Id = new Guid("11a7f9cc-4033-49ac-a9a7-370314727712"),
                            Answer = "At vero eos et accusamus et iusto",
                            CreateDttm = new DateTime(2022, 8, 8, 11, 20, 54, 232, DateTimeKind.Utc).AddTicks(7485),
                            CreatedBy = "SYSTEM",
                            IsDeleted = false,
                            Order = 3,
                            Question = "What are the Pooling Rules?",
                            UpdateDttm = new DateTime(2022, 8, 8, 11, 20, 54, 232, DateTimeKind.Utc).AddTicks(7486),
                            UpdatedBy = "SYSTEM"
                        },
                        new
                        {
                            Id = new Guid("43699d37-8b1f-4e7a-b976-d46a5f280ba8"),
                            Answer = "At vero eos et accusamus et iusto",
                            CreateDttm = new DateTime(2022, 8, 8, 11, 20, 54, 232, DateTimeKind.Utc).AddTicks(7487),
                            CreatedBy = "SYSTEM",
                            IsDeleted = false,
                            Order = 4,
                            Question = "What are the Available Pools?",
                            UpdateDttm = new DateTime(2022, 8, 8, 11, 20, 54, 232, DateTimeKind.Utc).AddTicks(7487),
                            UpdatedBy = "SYSTEM"
                        },
                        new
                        {
                            Id = new Guid("1cf62a72-e7cb-448c-a770-74ff05809d78"),
                            Answer = "At vero eos et accusamus et iusto",
                            CreateDttm = new DateTime(2022, 8, 8, 11, 20, 54, 232, DateTimeKind.Utc).AddTicks(7489),
                            CreatedBy = "SYSTEM",
                            IsDeleted = false,
                            Order = 5,
                            Question = "How are the Funds Distributed?",
                            UpdateDttm = new DateTime(2022, 8, 8, 11, 20, 54, 232, DateTimeKind.Utc).AddTicks(7489),
                            UpdatedBy = "SYSTEM"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
