// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using base_dao_api.Data;

#nullable disable

namespace base_dao_api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220808112121_v0.052")]
    partial class v0052
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("base_dao_api.Models.CodeDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CodeHeaderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateDttm")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("DetailCd")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdateDttm")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.HasIndex("CodeHeaderId");

                    b.HasIndex("DetailCd")
                        .IsUnique();

                    b.ToTable("CodeDetails");

                    b.HasData(
                        new
                        {
                            Id = new Guid("7d08feea-93c3-4ceb-9722-353b74b478d8"),
                            CodeHeaderId = new Guid("4624cb8f-ba13-4f87-89f4-7ee476abc524"),
                            CreateDttm = new DateTime(2022, 8, 8, 11, 21, 21, 587, DateTimeKind.Utc).AddTicks(7963),
                            CreatedBy = "SYSTEM",
                            Description = "System User",
                            DetailCd = "ROLE-SYSTEM",
                            IsDeleted = false,
                            UpdateDttm = new DateTime(2022, 8, 8, 11, 21, 21, 587, DateTimeKind.Utc).AddTicks(7963),
                            UpdatedBy = "SYSTEM"
                        },
                        new
                        {
                            Id = new Guid("9d9a7df4-f4ae-460c-878d-d8b9222ad154"),
                            CodeHeaderId = new Guid("4624cb8f-ba13-4f87-89f4-7ee476abc524"),
                            CreateDttm = new DateTime(2022, 8, 8, 11, 21, 21, 587, DateTimeKind.Utc).AddTicks(7973),
                            CreatedBy = "SYSTEM",
                            Description = "Admin User",
                            DetailCd = "ROLE-ADMIN",
                            IsDeleted = false,
                            UpdateDttm = new DateTime(2022, 8, 8, 11, 21, 21, 587, DateTimeKind.Utc).AddTicks(7973),
                            UpdatedBy = "SYSTEM"
                        },
                        new
                        {
                            Id = new Guid("5cfae912-4d88-4ce8-bef7-da795e54402c"),
                            CodeHeaderId = new Guid("4624cb8f-ba13-4f87-89f4-7ee476abc524"),
                            CreateDttm = new DateTime(2022, 8, 8, 11, 21, 21, 587, DateTimeKind.Utc).AddTicks(7975),
                            CreatedBy = "SYSTEM",
                            Description = "Normal User",
                            DetailCd = "ROLE-NORMAL",
                            IsDeleted = false,
                            UpdateDttm = new DateTime(2022, 8, 8, 11, 21, 21, 587, DateTimeKind.Utc).AddTicks(7976),
                            UpdatedBy = "SYSTEM"
                        },
                        new
                        {
                            Id = new Guid("55db0242-3c39-4967-b3db-d92cf00e0b39"),
                            CodeHeaderId = new Guid("47af2b2b-0e80-4f4e-9f3a-5dfb9dbd77a9"),
                            CreateDttm = new DateTime(2022, 8, 8, 11, 21, 21, 587, DateTimeKind.Utc).AddTicks(7977),
                            CreatedBy = "SYSTEM",
                            Description = "Pool OPEN",
                            DetailCd = "PSTATUS-OPEN",
                            IsDeleted = false,
                            UpdateDttm = new DateTime(2022, 8, 8, 11, 21, 21, 587, DateTimeKind.Utc).AddTicks(7978),
                            UpdatedBy = "SYSTEM"
                        },
                        new
                        {
                            Id = new Guid("7238ff2a-c0de-4a28-aeef-a2ef404d14d1"),
                            CodeHeaderId = new Guid("47af2b2b-0e80-4f4e-9f3a-5dfb9dbd77a9"),
                            CreateDttm = new DateTime(2022, 8, 8, 11, 21, 21, 587, DateTimeKind.Utc).AddTicks(7979),
                            CreatedBy = "SYSTEM",
                            Description = "Pool ONGOING",
                            DetailCd = "PSTATUS-ONGOING",
                            IsDeleted = false,
                            UpdateDttm = new DateTime(2022, 8, 8, 11, 21, 21, 587, DateTimeKind.Utc).AddTicks(7980),
                            UpdatedBy = "SYSTEM"
                        },
                        new
                        {
                            Id = new Guid("3121cea8-4779-44fa-a77b-b435d1048515"),
                            CodeHeaderId = new Guid("47af2b2b-0e80-4f4e-9f3a-5dfb9dbd77a9"),
                            CreateDttm = new DateTime(2022, 8, 8, 11, 21, 21, 587, DateTimeKind.Utc).AddTicks(7981),
                            CreatedBy = "SYSTEM",
                            Description = "Pool CLOSED",
                            DetailCd = "PSTATUS-CLOSED",
                            IsDeleted = false,
                            UpdateDttm = new DateTime(2022, 8, 8, 11, 21, 21, 587, DateTimeKind.Utc).AddTicks(7982),
                            UpdatedBy = "SYSTEM"
                        },
                        new
                        {
                            Id = new Guid("ad933d88-4db5-4972-86a1-c386daa4f83c"),
                            CodeHeaderId = new Guid("27779cb4-695d-418b-a280-12ef6d8f1606"),
                            CreateDttm = new DateTime(2022, 8, 8, 11, 21, 21, 587, DateTimeKind.Utc).AddTicks(7984),
                            CreatedBy = "SYSTEM",
                            Description = "Pool funder IN",
                            DetailCd = "PFSTATUS-IN",
                            IsDeleted = false,
                            UpdateDttm = new DateTime(2022, 8, 8, 11, 21, 21, 587, DateTimeKind.Utc).AddTicks(7984),
                            UpdatedBy = "SYSTEM"
                        },
                        new
                        {
                            Id = new Guid("19eae460-17ce-4fee-92c6-83e53aef18e7"),
                            CodeHeaderId = new Guid("27779cb4-695d-418b-a280-12ef6d8f1606"),
                            CreateDttm = new DateTime(2022, 8, 8, 11, 21, 21, 587, DateTimeKind.Utc).AddTicks(7986),
                            CreatedBy = "SYSTEM",
                            Description = "Pool funder OUT",
                            DetailCd = "PFTATUS-OUT",
                            IsDeleted = false,
                            UpdateDttm = new DateTime(2022, 8, 8, 11, 21, 21, 587, DateTimeKind.Utc).AddTicks(7986),
                            UpdatedBy = "SYSTEM"
                        },
                        new
                        {
                            Id = new Guid("b8ccf71d-0456-4695-be3f-bcdd66b81968"),
                            CodeHeaderId = new Guid("08d2e890-d7ad-4eb0-a710-37672a5cd98d"),
                            CreateDttm = new DateTime(2022, 8, 8, 11, 21, 21, 587, DateTimeKind.Utc).AddTicks(7988),
                            CreatedBy = "SYSTEM",
                            Description = "Pool activity status update",
                            DetailCd = "PASTATUS-SU",
                            IsDeleted = false,
                            UpdateDttm = new DateTime(2022, 8, 8, 11, 21, 21, 587, DateTimeKind.Utc).AddTicks(7988),
                            UpdatedBy = "SYSTEM"
                        },
                        new
                        {
                            Id = new Guid("8d682f80-f9b5-4fa4-a91e-7df26a7e80d3"),
                            CodeHeaderId = new Guid("08d2e890-d7ad-4eb0-a710-37672a5cd98d"),
                            CreateDttm = new DateTime(2022, 8, 8, 11, 21, 21, 587, DateTimeKind.Utc).AddTicks(7993),
                            CreatedBy = "SYSTEM",
                            Description = "Pool activity descriptions update",
                            DetailCd = "PASTATUS-PU",
                            IsDeleted = false,
                            UpdateDttm = new DateTime(2022, 8, 8, 11, 21, 21, 587, DateTimeKind.Utc).AddTicks(7993),
                            UpdatedBy = "SYSTEM"
                        },
                        new
                        {
                            Id = new Guid("2b5d72a4-ebd3-436e-a28e-4a34565acd6d"),
                            CodeHeaderId = new Guid("08d2e890-d7ad-4eb0-a710-37672a5cd98d"),
                            CreateDttm = new DateTime(2022, 8, 8, 11, 21, 21, 587, DateTimeKind.Utc).AddTicks(7995),
                            CreatedBy = "SYSTEM",
                            Description = "Pool activity funders update",
                            DetailCd = "PASTATUS-FU",
                            IsDeleted = false,
                            UpdateDttm = new DateTime(2022, 8, 8, 11, 21, 21, 587, DateTimeKind.Utc).AddTicks(7995),
                            UpdatedBy = "SYSTEM"
                        });
                });

            modelBuilder.Entity("base_dao_api.Models.CodeHeader", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateDttm")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("HeaderCd")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdateDttm")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.HasIndex("HeaderCd")
                        .IsUnique();

                    b.ToTable("CodeHeaders");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4624cb8f-ba13-4f87-89f4-7ee476abc524"),
                            CreateDttm = new DateTime(2022, 8, 8, 11, 21, 21, 587, DateTimeKind.Utc).AddTicks(7369),
                            CreatedBy = "SYSTEM",
                            Description = "CodeHeader for User Roles",
                            HeaderCd = "ROLE",
                            IsDeleted = false,
                            UpdateDttm = new DateTime(2022, 8, 8, 11, 21, 21, 587, DateTimeKind.Utc).AddTicks(7372),
                            UpdatedBy = "SYSTEM"
                        },
                        new
                        {
                            Id = new Guid("47af2b2b-0e80-4f4e-9f3a-5dfb9dbd77a9"),
                            CreateDttm = new DateTime(2022, 8, 8, 11, 21, 21, 587, DateTimeKind.Utc).AddTicks(7377),
                            CreatedBy = "SYSTEM",
                            Description = "CodeHeader for Pool Statuses",
                            HeaderCd = "PSTATUS",
                            IsDeleted = false,
                            UpdateDttm = new DateTime(2022, 8, 8, 11, 21, 21, 587, DateTimeKind.Utc).AddTicks(7377),
                            UpdatedBy = "SYSTEM"
                        },
                        new
                        {
                            Id = new Guid("27779cb4-695d-418b-a280-12ef6d8f1606"),
                            CreateDttm = new DateTime(2022, 8, 8, 11, 21, 21, 587, DateTimeKind.Utc).AddTicks(7379),
                            CreatedBy = "SYSTEM",
                            Description = "CodeHeader for Pool Funder Statuses",
                            HeaderCd = "PFSTATUS",
                            IsDeleted = false,
                            UpdateDttm = new DateTime(2022, 8, 8, 11, 21, 21, 587, DateTimeKind.Utc).AddTicks(7379),
                            UpdatedBy = "SYSTEM"
                        },
                        new
                        {
                            Id = new Guid("08d2e890-d7ad-4eb0-a710-37672a5cd98d"),
                            CreateDttm = new DateTime(2022, 8, 8, 11, 21, 21, 587, DateTimeKind.Utc).AddTicks(7380),
                            CreatedBy = "SYSTEM",
                            Description = "CodeHeader for Pool Activity Statuses",
                            HeaderCd = "PASTATUS",
                            IsDeleted = false,
                            UpdateDttm = new DateTime(2022, 8, 8, 11, 21, 21, 587, DateTimeKind.Utc).AddTicks(7381),
                            UpdatedBy = "SYSTEM"
                        });
                });

            modelBuilder.Entity("base_dao_api.Models.Faq", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime>("CreateDttm")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime?>("UpdateDttm")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.HasIndex("Order")
                        .IsUnique();

                    b.ToTable("Faqs");

                    b.HasData(
                        new
                        {
                            Id = new Guid("51c7df49-86e3-4dec-ae9a-48f152c78d31"),
                            Answer = "At vero eos et accusamus et iusto",
                            CreateDttm = new DateTime(2022, 8, 8, 11, 21, 21, 587, DateTimeKind.Utc).AddTicks(8431),
                            CreatedBy = "SYSTEM",
                            IsDeleted = false,
                            Order = 1,
                            Question = "What is Wick's Crew?",
                            UpdateDttm = new DateTime(2022, 8, 8, 11, 21, 21, 587, DateTimeKind.Utc).AddTicks(8432),
                            UpdatedBy = "SYSTEM"
                        },
                        new
                        {
                            Id = new Guid("ae3b3e6c-396c-4873-a3c2-ff6723057088"),
                            Answer = "At vero eos et accusamus et iusto",
                            CreateDttm = new DateTime(2022, 8, 8, 11, 21, 21, 587, DateTimeKind.Utc).AddTicks(8435),
                            CreatedBy = "SYSTEM",
                            IsDeleted = false,
                            Order = 2,
                            Question = "What are Pooling Considerations?",
                            UpdateDttm = new DateTime(2022, 8, 8, 11, 21, 21, 587, DateTimeKind.Utc).AddTicks(8436),
                            UpdatedBy = "SYSTEM"
                        },
                        new
                        {
                            Id = new Guid("3a3a5773-4b74-4be1-8436-83fea7f4e099"),
                            Answer = "At vero eos et accusamus et iusto",
                            CreateDttm = new DateTime(2022, 8, 8, 11, 21, 21, 587, DateTimeKind.Utc).AddTicks(8437),
                            CreatedBy = "SYSTEM",
                            IsDeleted = false,
                            Order = 3,
                            Question = "What are the Pooling Rules?",
                            UpdateDttm = new DateTime(2022, 8, 8, 11, 21, 21, 587, DateTimeKind.Utc).AddTicks(8437),
                            UpdatedBy = "SYSTEM"
                        },
                        new
                        {
                            Id = new Guid("be37afc6-4663-4357-857e-165ed0667d63"),
                            Answer = "At vero eos et accusamus et iusto",
                            CreateDttm = new DateTime(2022, 8, 8, 11, 21, 21, 587, DateTimeKind.Utc).AddTicks(8439),
                            CreatedBy = "SYSTEM",
                            IsDeleted = false,
                            Order = 4,
                            Question = "What are the Available Pools?",
                            UpdateDttm = new DateTime(2022, 8, 8, 11, 21, 21, 587, DateTimeKind.Utc).AddTicks(8439),
                            UpdatedBy = "SYSTEM"
                        },
                        new
                        {
                            Id = new Guid("867c592d-fe25-4360-98bf-0d6f9f9472b3"),
                            Answer = "At vero eos et accusamus et iusto",
                            CreateDttm = new DateTime(2022, 8, 8, 11, 21, 21, 587, DateTimeKind.Utc).AddTicks(8441),
                            CreatedBy = "SYSTEM",
                            IsDeleted = false,
                            Order = 5,
                            Question = "How are the Funds Distributed?",
                            UpdateDttm = new DateTime(2022, 8, 8, 11, 21, 21, 587, DateTimeKind.Utc).AddTicks(8441),
                            UpdatedBy = "SYSTEM"
                        });
                });

            modelBuilder.Entity("base_dao_api.Models.Pool", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateDttm")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<decimal>("MinInvestment")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("StatusId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdateDttm")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.HasIndex("StatusId");

                    b.ToTable("Pools");
                });

            modelBuilder.Entity("base_dao_api.Models.PoolActivity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateDttm")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("PoolId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("StatusId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdateDttm")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.HasIndex("PoolId");

                    b.HasIndex("StatusId");

                    b.ToTable("PoolActivities");
                });

            modelBuilder.Entity("base_dao_api.Models.PoolFunder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("AmtInvested")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("AmtReturned")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreateDttm")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("PoolId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("StatusId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdateDttm")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("WalletAddress")
                        .IsRequired()
                        .HasMaxLength(42)
                        .HasColumnType("nvarchar(42)");

                    b.HasKey("Id");

                    b.HasIndex("PoolId");

                    b.HasIndex("StatusId");

                    b.ToTable("PoolFunders");
                });

            modelBuilder.Entity("base_dao_api.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateDttm")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime?>("UpdateDttm")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("WalletAddress")
                        .IsRequired()
                        .HasMaxLength(42)
                        .HasColumnType("nvarchar(42)");

                    b.HasKey("Id");

                    b.HasIndex("WalletAddress")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8b2a0f70-5386-4746-9440-514867f730c1"),
                            CreateDttm = new DateTime(2022, 8, 8, 11, 21, 21, 587, DateTimeKind.Utc).AddTicks(8938),
                            CreatedBy = "SYSTEM",
                            IsDeleted = false,
                            Name = "SYSTEM",
                            UpdateDttm = new DateTime(2022, 8, 8, 11, 21, 21, 587, DateTimeKind.Utc).AddTicks(8938),
                            UpdatedBy = "SYSTEM",
                            WalletAddress = "0x8c268f32D7F129ac0D9FB1E5B490d90810dFa446"
                        },
                        new
                        {
                            Id = new Guid("ff3b8dd0-3613-425d-9cc2-e553caab4244"),
                            CreateDttm = new DateTime(2022, 8, 8, 11, 21, 21, 587, DateTimeKind.Utc).AddTicks(8945),
                            CreatedBy = "SYSTEM",
                            IsDeleted = false,
                            Name = "ADMIN-1",
                            UpdateDttm = new DateTime(2022, 8, 8, 11, 21, 21, 587, DateTimeKind.Utc).AddTicks(8945),
                            UpdatedBy = "SYSTEM",
                            WalletAddress = "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266"
                        });
                });

            modelBuilder.Entity("base_dao_api.Models.UserRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateDttm")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdateDttm")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("UserRoles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("16524b67-80c1-406c-9d42-285bf8cf7157"),
                            CreateDttm = new DateTime(2022, 8, 8, 11, 21, 21, 588, DateTimeKind.Utc).AddTicks(78),
                            CreatedBy = "SYSTEM",
                            IsDeleted = false,
                            RoleId = new Guid("7d08feea-93c3-4ceb-9722-353b74b478d8"),
                            UpdateDttm = new DateTime(2022, 8, 8, 11, 21, 21, 588, DateTimeKind.Utc).AddTicks(78),
                            UpdatedBy = "SYSTEM",
                            UserId = new Guid("8b2a0f70-5386-4746-9440-514867f730c1")
                        },
                        new
                        {
                            Id = new Guid("fb5d3d7a-2691-4119-9374-9afe0343d935"),
                            CreateDttm = new DateTime(2022, 8, 8, 11, 21, 21, 588, DateTimeKind.Utc).AddTicks(81),
                            CreatedBy = "SYSTEM",
                            IsDeleted = false,
                            RoleId = new Guid("9d9a7df4-f4ae-460c-878d-d8b9222ad154"),
                            UpdateDttm = new DateTime(2022, 8, 8, 11, 21, 21, 588, DateTimeKind.Utc).AddTicks(81),
                            UpdatedBy = "SYSTEM",
                            UserId = new Guid("ff3b8dd0-3613-425d-9cc2-e553caab4244")
                        });
                });

            modelBuilder.Entity("base_dao_api.Models.CodeDetail", b =>
                {
                    b.HasOne("base_dao_api.Models.CodeHeader", "CodeHeader")
                        .WithMany("CodeDetails")
                        .HasForeignKey("CodeHeaderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CodeHeader");
                });

            modelBuilder.Entity("base_dao_api.Models.Pool", b =>
                {
                    b.HasOne("base_dao_api.Models.CodeDetail", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Status");
                });

            modelBuilder.Entity("base_dao_api.Models.PoolActivity", b =>
                {
                    b.HasOne("base_dao_api.Models.Pool", "Pool")
                        .WithMany("PoolActivities")
                        .HasForeignKey("PoolId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("base_dao_api.Models.CodeDetail", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pool");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("base_dao_api.Models.PoolFunder", b =>
                {
                    b.HasOne("base_dao_api.Models.Pool", "Pool")
                        .WithMany("PoolFunders")
                        .HasForeignKey("PoolId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("base_dao_api.Models.CodeDetail", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pool");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("base_dao_api.Models.UserRole", b =>
                {
                    b.HasOne("base_dao_api.Models.CodeDetail", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("base_dao_api.Models.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("base_dao_api.Models.CodeHeader", b =>
                {
                    b.Navigation("CodeDetails");
                });

            modelBuilder.Entity("base_dao_api.Models.Pool", b =>
                {
                    b.Navigation("PoolActivities");

                    b.Navigation("PoolFunders");
                });

            modelBuilder.Entity("base_dao_api.Models.User", b =>
                {
                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
